name: Build and Push Frontend Docker Image

on:
  push:
    branches: [web]

jobs:
  build-frontend:
    runs-on: ubuntu-latest
    env:
      DOCKER_BUILDKIT: 1
      APP_NAME: cybersapient-frontend
    steps:
      - name: Add dynamic envs
        run: |
          echo "SHORT_SHA=`echo ${GITHUB_SHA} | cut -c1-7`" >> $GITHUB_ENV
      
      # Checkout repository
      - name: Checkout
        uses: actions/checkout@v4
      
      # Login to Docker Hub
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      
      # Build and push frontend Docker image
      - name: Build and push Frontend Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./frontend
          push: true
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/cybersapient-frontend:${{ env.SHORT_SHA }}
            ${{ secrets.DOCKER_USERNAME }}/cybersapient-frontend:latest
          build-args: |
            BUILDKIT_INLINE_CACHE=1
      
      # Optional: Clean up
      - name: Clean up
        run: |
          docker system prune -f