name: Build and Push Backend Docker Image

on:
  push:
    branches: [server]

jobs:
  build-backend:
    runs-on: ubuntu-latest
    env:
      DOCKER_BUILDKIT: 1
      APP_NAME: cybersapient-backend
    steps:
      - name: Add dynamic envs
        run: |
          echo "SHORT_SHA=`echo ${GITHUB_SHA} | cut -c1-7`" >> $GITHUB_ENV
      
      # Checkout repository
      - name: Checkout
        uses: actions/checkout@v4
      
      # Python code formatting check (optional)
      - name: Check Python code formatting
        uses: psf/black@stable
        with:
          options: "--check --verbose"
          src: "./backend"
          jupyter: false
          version: "24.10.0"
      
      # Login to Docker Hub
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      
      # Build and push backend Docker image
      - name: Build and push Backend Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./backend
          push: true
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/cybersapient-backend:${{ env.SHORT_SHA }}
            ${{ secrets.DOCKER_USERNAME }}/cybersapient-backend:latest
          build-args: |
            BUILDKIT_INLINE_CACHE=1
      
      # Optional: Clean up
      - name: Clean up
        run: |
          docker system prune -f